apiVersion: v1
kind: ServiceAccount
metadata:
  name: disercomi-frontend
  namespace: mineco

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-ingress-disercomi
#   namespace: nginx-ingress
# spec:
#   type: LoadBalancer
#   externalIPs:
#     - 128.5.4.27
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#       name: http
#     - protocol: TCP
#       port: 443
#       targetPort: 443
#       name: https
#   selector:
#     app: nginx-ingress

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: disercomi-pv-pvc
  namespace: mineco
  labels:
    name: disercomi-pv-pvc
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 128.5.8.222
    path: "/deployment/disercomi/frontend"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disercomi-pv-pvc
  namespace: mineco
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: disercomi-pv-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: disercomi-frontend-server
  namespace: mineco
  labels:
    run: disercomi-frontend-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: disercomi-frontend-server
  template:
    metadata:
      labels:
        run: disercomi-frontend-server
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 128.5.8.26
        searches:
          - mineco-dev.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      containers:
        - name: disercomi-frontend-server
          image: jjolon/disercome_frontend
          resources:
            requests:
              memory: "Gi"
              cpu: "200m"
            limits:
              memory: "3Gi"
              cpu: "700m"
          ports:
            - containerPort: 443
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: "/var/www/html"
              name: vol-php-frontend
      volumes:
        - name: vol-php-frontend
          persistentVolumeClaim:
            claimName: disercomi-pv-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: disercomi-frontend-server
  namespace: mineco
  labels:
    app.kubernetes.io/name: disercomi-frontend-server
    app.kubernetes.io/part-of: disercomi-frontend-server
spec:
  type: LoadBalancer
  externalIPs:
    - 128.5.4.27
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: listener-2
      port: 443
      protocol: TCP
  selector:
    run: disercomi-frontend-server

