USE dm_mnt_trade;
ALTER TABLE trd_acuerdo_comercial DROP FOREIGN KEY FK_ACRDCOM_TPOACCOM;
ALTER TABLE trd_acuerdo_comercial ADD CONSTRAINT FK_ACRDCOM_TPOACCOM FOREIGN KEY (ID_TIPO_ACUERDO_COM) REFERENCES trd_tipo_acuerdo_comercial (ID);

ALTER TABLE trd_documento_aprobacion DROP FOREIGN KEY FK_DOCAPR_SSPP;
ALTER TABLE trd_documento_aprobacion ADD CONSTRAINT FK_DOCAPR_SSPP FOREIGN KEY (ID_SSPP) REFERENCES trd_sspp (ID);

ALTER TABLE trd_hscode DROP FOREIGN KEY FK_HSDCODE_CAPITULO;
ALTER TABLE trd_hscode DROP FOREIGN KEY FK_HSDCODE_PARTIDA;
ALTER TABLE trd_hscode DROP FOREIGN KEY FK_HSDCODE_SUBPRTD;
ALTER TABLE trd_hscode DROP FOREIGN KEY FK_HSDCODE_SUBPRTDNC;
ALTER TABLE trd_hscode ADD CONSTRAINT FK_HSDCODE_CAPITULO FOREIGN KEY (ID_CAPITULO) REFERENCES trd_capitulo (ID);
ALTER TABLE trd_hscode ADD CONSTRAINT FK_HSDCODE_PARTIDA FOREIGN KEY (ID_PARTIDA) REFERENCES trd_partida (ID);
ALTER TABLE trd_hscode ADD CONSTRAINT FK_HSDCODE_SUBPRTD FOREIGN KEY (ID_SUBPARTIDA) REFERENCES trd_subpartida (ID);
ALTER TABLE trd_hscode ADD CONSTRAINT FK_HSDCODE_SUBPRTDNC FOREIGN KEY (ID_SUBPARTIDA_NC) REFERENCES trd_subpartida_nc (ID);

ALTER TABLE trd_hscode_acuerdo DROP FOREIGN KEY FK_HSCACDR_HSCODE;
ALTER TABLE trd_hscode_acuerdo DROP FOREIGN KEY FK_HSCACRD_ACRDCOM;
ALTER TABLE trd_hscode_acuerdo ADD CONSTRAINT FK_HSCACDR_HSCODE FOREIGN KEY (ID_HSCODDE) REFERENCES trd_hscode (ID);
ALTER TABLE trd_hscode_acuerdo ADD CONSTRAINT FK_HSCACRD_ACRDCOM FOREIGN KEY (ID_ACUERDO_COMERCIAL) REFERENCES trd_acuerdo_comercial (ID);

ALTER TABLE trd_hscode_matriz DROP FOREIGN KEY FK_HSCDMTZ_HSCODE;
ALTER TABLE trd_hscode_matriz DROP FOREIGN KEY FK_HSCDMTZ_MTZVB;
ALTER TABLE trd_hscode_matriz ADD CONSTRAINT FK_HSCDMTZ_HSCODE FOREIGN KEY (ID_HSCODE) REFERENCES trd_hscode (ID);
ALTER TABLE trd_hscode_matriz ADD CONSTRAINT FK_HSCDMTZ_MTZVB FOREIGN KEY (ID_MATRIZ_VB) REFERENCES trd_matriz_vb (ID);

ALTER TABLE trd_matriz_documento DROP FOREIGN KEY FK_MTZDOC_DOCAPR;
ALTER TABLE trd_matriz_documento DROP FOREIGN KEY FK_MTZDOC_MTZVB;
ALTER TABLE trd_matriz_documento ADD CONSTRAINT FK_MTZDOC_DOCAPR FOREIGN KEY (ID_DOC_APROBACION) REFERENCES trd_documento_aprobacion (ID);
ALTER TABLE trd_matriz_documento ADD CONSTRAINT FK_MTZDOC_MTZVB FOREIGN KEY (ID_MATRIZ_VB) REFERENCES trd_matriz_vb (ID);

ALTER TABLE trd_matriz_producto DROP FOREIGN KEY FK_MTZPROD_MTZVB;
ALTER TABLE trd_matriz_producto DROP FOREIGN KEY FK_MTZPROD_PROD;
ALTER TABLE trd_matriz_producto ADD CONSTRAINT FK_MTZPROD_MTZVB FOREIGN KEY (ID_MATRIZ_VB) REFERENCES trd_matriz_vb (ID);
ALTER TABLE trd_matriz_producto ADD CONSTRAINT FK_MTZPROD_PROD FOREIGN KEY (ID_PRODUCTO) REFERENCES trd_producto (ID);

ALTER TABLE trd_matriz_vb DROP FOREIGN KEY FK_MTZVB_CARESPEC;
ALTER TABLE trd_matriz_vb DROP FOREIGN KEY FK_MTZVB_USOPREV;
ALTER TABLE trd_matriz_vb ADD CONSTRAINT FK_MTZVB_CARESPEC FOREIGN KEY (ID_CAR_ESPECIAL) REFERENCES trd_caracteristica_especial (ID);
ALTER TABLE trd_matriz_vb ADD CONSTRAINT FK_MTZVB_USOPREV FOREIGN KEY (ID_USO_PREVISTO) REFERENCES trd_uso_previsto (ID);

ALTER TABLE trd_pais_matriz DROP FOREIGN KEY FK_MTZPAIS_MTZVB;
ALTER TABLE trd_pais_matriz DROP FOREIGN KEY FK_MTZPAIS_PAIS;
ALTER TABLE trd_pais_matriz ADD CONSTRAINT FK_MTZPAIS_MTZVB FOREIGN KEY (ID_MATRIZ_VB) REFERENCES trd_matriz_vb (ID);
ALTER TABLE trd_pais_matriz ADD CONSTRAINT FK_MTZPAIS_PAIS FOREIGN KEY (ID_PAIS) REFERENCES trd_pais (ID);

ALTER TABLE trd_partida DROP FOREIGN KEY FK_PARTIDA_CAPITULO;
ALTER TABLE trd_partida ADD CONSTRAINT FK_PARTIDA_CAPITULO FOREIGN KEY (ID_CAPITULO) REFERENCES trd_capitulo (ID);

ALTER TABLE trd_producto DROP FOREIGN KEY FK_PRODUCTO_HSCODE;
ALTER TABLE trd_producto ADD CONSTRAINT FK_PRODUCTO_HSCODE FOREIGN KEY (ID_HSCODE) REFERENCES trd_hscode (ID);

ALTER TABLE trd_producto_atributo DROP FOREIGN KEY FK_ATRPROD_PRODUCTO;
ALTER TABLE trd_producto_atributo ADD CONSTRAINT FK_ATRPROD_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES trd_producto (ID);

ALTER TABLE trd_subpartida DROP FOREIGN KEY FK_SUBPRTD_PARTIDA;
ALTER TABLE trd_subpartida ADD CONSTRAINT FK_SUBPRTD_PARTIDA FOREIGN KEY (ID_PARTIDA) REFERENCES trd_partida (ID);

ALTER TABLE trd_subpartida_nc DROP FOREIGN KEY FK_SUBPRTDNC_SUBPRTD;
ALTER TABLE trd_subpartida_nc ADD CONSTRAINT FK_SUBPRTDNC_SUBPRTD FOREIGN KEY (ID_SUBPARTIDA) REFERENCES trd_subpartida (ID);


USE dm_vuc_trade;

ALTER TABLE tad_expediente_documento DROP FOREIGN KEY FK_tad_expediente_documento_tad_documento;
ALTER TABLE tad_expediente_documento ADD CONSTRAINT FK_tad_expediente_documento_tad_documento FOREIGN KEY (ID_DOCUMENTO) REFERENCES tad_documento (ID);

ALTER TABLE tad_expediente_documento DROP FOREIGN KEY FK_tad_expediente_documento_tad_expediente_base;
ALTER TABLE tad_expediente_documento ADD CONSTRAINT FK_tad_expediente_documento_tad_expediente_base FOREIGN KEY (ID_EXPEDIENTE) REFERENCES tad_expediente_base (ID);

ALTER TABLE tad_notificacion DROP FOREIGN KEY FK_tad_notificacion_tad_expediente_base;
ALTER TABLE tad_notificacion ADD CONSTRAINT FK_tad_notificacion_tad_expediente_base FOREIGN KEY (ID_EXPEDIENTE_BASE) REFERENCES tad_expediente_base (ID);

ALTER TABLE tad_t_tramite_t_documento DROP FOREIGN KEY FK_tad_t_tramite_t_documento_tad_tipo_documento;
ALTER TABLE tad_t_tramite_t_documento ADD CONSTRAINT FK_tad_t_tramite_t_documento_tad_tipo_documento FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES tad_tipo_documento (ID);
