apiVersion: v1
kind: ServiceAccount
metadata:
  name: otrs-qa
  namespace: mineco-qa
---
#  INGRESS MINECO
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-otrs
  namespace: nginx-ingress
spec:
  type: LoadBalancer
  externalIPs:
  - 128.5.4.11
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
  selector:
    app: nginx-ingress


---

# # VOLUME DATA
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: otrs-deploy-qa
#   namespace: mineco-qa
#   labels:
#     name: otrs-deploy-qa
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 20Gi
#   accessModes:
#     - ReadWriteOnce
#   nfs:
#     server: 128.5.8.222
#     path: "/deployment/qa/otrs"

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: otrs-deploy-qa
#   namespace: mineco-qa
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
#   selector:
#     matchLabels:
#       name: otrs-deploy-qa

# ---
# DEPLOYMENT APP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otrs-qa
  namespace: mineco-qa
  labels:
    run: otrs-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      run: otrs-qa
  template:
    metadata:
      labels:
        run: otrs-qa
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 128.5.8.26
        searches:
          - mineco-dev.svc.cluster.local
          - svc.cluster.local 
          - cluster.local
      containers:
      - name: otrs-server-qa
        image: juanluisbaptiste/otrs:6.0.27
        env:
          - name: MYSQL_HOSTNAME
            value: mysql
          - name: MYSQL_USERNAME
            value: root
          - name: MYSQL_PASSWORD
            value: ligero
          - name: CUSTOMER_ID
            value: ligero
          - name: OTRS_SYSTEM_ID
            value: "10"
          - name: OTRS_DEFAULT_LANGUAGE
            value: en
          - name: INSTALL
            value: "1"
        ports:
          - containerPort: 443
            protocol: TCP
          - containerPort: 80
            protocol: TCP
      #   volumeMounts:
      #       - mountPath: "/var/www/html"
      #         name: otrs-qa-vol
      # volumes:
      #   - name: otrs-qa-vol
      #     persistentVolumeClaim:
      #       claimName: otrs-deploy-qa


---
apiVersion: v1
kind: Service
metadata:
  name: otrs-qa
  namespace: mineco-qa
  labels:
    app.kubernetes.io/name: otrs-qa
    app.kubernetes.io/part-of: otrs-qa
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: listener-2
      port: 443
      protocol: TCP
  selector:
    run: otrs-qa
