apiVersion: v1
kind: ServiceAccount
metadata:
  name: dti-qa
  namespace: mineco-qa
---
#  INGRESS MINECO
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-dti
  namespace: nginx-ingress
spec:
  type: LoadBalancer
  externalIPs:
  - 128.5.4.13
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
  selector:
    app: nginx-ingress


---

# VOLUME DATA
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dti-deploy-qa
  namespace: mineco-qa
  labels:
    name: dti-deploy-qa
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 128.5.8.222
    path: "/deployment/qa/dti"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dti-deploy-qa
  namespace: mineco-qa
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: dti-deploy-qa

---
# DEPLOYMENT APP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dti-qa
  namespace: mineco-qa
  labels:
    run: dti-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dti-qa
  template:
    metadata:
      labels:
        run: dti-qa
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 128.5.8.26
        searches:
          - mineco-dev.svc.cluster.local
          - svc.cluster.local 
          - cluster.local
      containers:
      - name: dti-server-qa
        image: jjolon/php-full:latest
        ports:
          - containerPort: 443
            protocol: TCP
          - containerPort: 80
            protocol: TCP
        volumeMounts:
            - mountPath: "/var/www/html"
              name: dti-qa-vol
      volumes:
        - name: dti-qa-vol
          persistentVolumeClaim:
            claimName: dti-deploy-qa


---
apiVersion: v1
kind: Service
metadata:
  name: dti-qa
  namespace: mineco-qa
  labels:
    app.kubernetes.io/name: dti-qa
    app.kubernetes.io/part-of: dti-qa
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: listener-2
      port: 443
      protocol: TCP
  selector:
    run: dti-qa
