/* 
- DEO -
*/
USE dm_deo_egov;

ALTER TABLE cc_acknowledge
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_address
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_audit
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_autorizacion
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_bulto
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_chapter
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_commoneda
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_cuenta
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_declaracion
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_detaileda
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_detalle_cuota
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_detalles_documento_instalacion
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_detallespuerto
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_documento_apoyo
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_financiero
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_header
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_heading
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_hoja_anexa
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_hs_code_matriz_cc
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_hscode
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_insumos_datpa
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_interop_header
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_lista_documento_ingreso
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_lista_productos_di
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_manifiesto
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_medio_transporte
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_mercancia
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_observacion
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_operation
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_participantes
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_product
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_product_attributes
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_product_attributes_operation
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_product_operation
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_regimen_susp
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_reserva
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_resumen_declaracion_ingreso
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_resumen_op_dus
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_subheading
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_transport
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_view_destinos_asociados
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_view_resumen
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_view_resumen_impo
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_view_vistos_buenos
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_almacenista_din
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_bulto_da
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_com_transp_dus
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_dec_doc_ing_env
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_declaracion_din
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_destino_doc_ing_envio
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_det_puertos_da
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_documento
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_documento_apoyo_da
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_documento_ingreso_envio
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_documento_ingreso_oig
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_financieroda
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_instalacion_doc_ing_envio
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_mercancia_da
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_observacion_da
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_observacion_doc_ingreso_envio
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_origen_doc_ing
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_otro_impuesto_din
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_participante_secundario
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_participantes_da
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_prod_doc_ing_env
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_product_attribute_da
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_product_da
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_reg_suspensivo_da
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE cc_vista_totales_declaracion
 CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE df_clob_text
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE df_component
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE df_component_multivalue
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE df_component_type
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE df_dynamic_component
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE df_dynamic_form
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE df_form
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE df_form_comp_value
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE df_form_component
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE df_group
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE df_group_component
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE df_transaction
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_archivo_de_trabajo
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_aviso
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_documento
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_documento_adjunto
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_documento_solicitud
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_historial
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_numeracionespecial
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_numeracionespecial_aud
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_numerosusados
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_plantilla
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_proceso_log
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_tipodocumento
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_tipodocumento_aud
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_tipodocumento_familia
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_tipodocumento_reparticion
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_usuario_plantilla
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE df_attribute
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE CCOO_COMUNICACION
 CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE ccoo_comunicacion_destino
 CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE df_attribute
 CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE df_dynamic_constraint
 CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_aviso
 CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE gedo_hist_visualizacion
 CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
 
 

/*
-TE -
*/

USE dm_te_egov;

ALTER TABLE actividad
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE actividad_param
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE documento
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE documento_de_identidad
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE ee_arch_trabajo_visualizacion
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE ee_archivo_de_trabajo
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE ee_archivo_remision
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE ee_aud_tarea_migracion_error
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE ee_expediente_electronico
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE ee_subprocess
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE ee_subprocess_production
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE ee_tarea_paralelo
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE ee_tipos_archivo_trabajo
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE expedienteasociado
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE generar_copia
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE historialoperacion
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE solicitud_expediente
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE te_log_esb
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE te_operacion
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE te_subprocess
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE te_subprocess_production
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE te_tipo_operacion
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE tipo_actividad
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE tipo_documento
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE tipo_documento_depuracion
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE trata
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE trata_auditoria
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE trata_integracion_reparticion
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE trata_reparticion_auditoria
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE usuario_migracion
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE wd_bitacora
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE trata_tipo_documento
CHANGE ID_TRATA_TIPO_DOCUMENTO ID_TRATA_TIPO_DOCUMENTO INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE trata_tipo_documento_auditoria  
CHANGE ID_TRATA_TIPO_DOCUMENTO ID_TRATA_TIPO_DOCUMENTO INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE te_operacion_ee 
CHANGE ID_EXPEDIENTE_ELECTRONICO ID_EXPEDIENTE_ELECTRONICO INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE solicitante  
CHANGE ID_SOLICITANTE ID_SOLICITANTE INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE ee_reparticion_participante 
CHANGE ID_REPARTICION ID_REPARTICION INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE ee_aud_tarea_migracion 
CHANGE ID_TAREA ID_TAREA INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE ee_auditoria_de_consulta 
CHANGE ID_AUDITORIA ID_AUDITORIA INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE ee_auditoria_notificacion 
CHANGE ID_AUDITORIA ID_AUDITORIA INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE trata_reparticion 
CHANGE ID_TRATA ID_TRATA INT(19) AUTO_INCREMENT NOT NULL;


/*
-EDT -
*/

USE dm_edt_egov;


ALTER TABLE edt_cargos
CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE edt_datos_usuario
CHANGE ID_DATO_USUARIO ID_DATO_USUARIO INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE edt_periodo_licencia
CHANGE ID_PERIODO_LICENCIA ID_PERIODO_LICENCIA INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE edt_rol
CHANGE EDTRL_ID EDTRL_ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE edt_sade_actuacion
CHANGE ID_ACTUACION ID_ACTUACION INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE edt_sade_actuacion_audi
CHANGE ID_ACTUACION_AUDI ID_ACTUACION_AUDI INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE edt_sade_estructura
CHANGE ID_ESTRUCTURA ID_ESTRUCTURA INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE edt_sade_jurisdiccion
CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE edt_sade_reparticion
CHANGE ID_REPARTICION ID_REPARTICION INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE edt_sade_reparticion_seleccionada
CHANGE ID_REPARTICION_SELECCIONADA ID_REPARTICION_SELECCIONADA INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE edt_sade_sector_interno
CHANGE ID_SECTOR_INTERNO ID_SECTOR_INTERNO INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE edt_sade_sector_usuario
CHANGE ID_SECTOR_USUARIO ID_SECTOR_USUARIO INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE edt_sade_uai
CHANGE ID_UAI ID_UAI INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE edt_sade_usr_repa_habilitada
CHANGE ID_USR_REPA_HABILITADA ID_USR_REPA_HABILITADA INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE eu_aplicacion
CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE eu_feriados
CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE eu_feriados_audi
CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE eu_novedad
CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE eu_novedad_hist
CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE eu_usuario_buzongrupal
CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE eu_usuario_frecuencias
CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE eu_usuario_missistemas
CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE eu_usuario_missupervisados
CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE eu_usuario_mistareas
CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE sade_app_alive_logger
CHANGE ID ID INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE tad_busqueda_auditoria
CHANGE ID_BUSQUEDA_AUDITORIA ID_BUSQUEDA_AUDITORIA INT(10) AUTO_INCREMENT NOT NULL;


/*
- MNT -
*/

USE dm_mnt_egov;


ALTER TABLE trd_producto_atributo
CHANGE ID ID bigint(20) AUTO_INCREMENT NOT NULL;



/*
- NUMERADOR -
*/

USE dm_numerador_egov;

ALTER TABLE numero_proceso_batch 
CHANGE ID_PROCESO_BATCH ID_PROCESO_BATCH INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE numero_sade 
CHANGE ID_NUMERO_SADE ID_NUMERO_SADE INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE numero_sade_caratula 
CHANGE ID_NUMERO_SADE_CARATULA ID_NUMERO_SADE_CARATULA INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE numero_sade_secuencia 
CHANGE ID_SECUENCIA ID_SECUENCIA INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE numero_sade_trabajo 
CHANGE ID_SECUENCIA_USADA_DIARIA ID_SECUENCIA_USADA_DIARIA INT(10) AUTO_INCREMENT NOT NULL;
ALTER TABLE numero_sistemas_sade 
CHANGE ID_SISTEMA ID_SISTEMA INT(10) AUTO_INCREMENT NOT NULL;


/*
- VUC -
*/

USE dm_vuc_egov;

ALTER TABLE tad_apoderado_persona
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE tad_campo
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE tad_contenido
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE tad_documento 
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE tad_expediente_base
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE tad_expediente_reintento
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE tad_notificacion 
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE tad_persona
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE tad_t_tramite_t_documento
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE tad_tarea
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE tad_tipo_documento
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE tad_tipo_documento_identidad
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE tad_tipo_tramite
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE vuc_t_tramite_t_form
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE vuc_form_type 
 CHANGE ID_TYPE_FORM ID_TYPE_FORM INT(19) AUTO_INCREMENT NOT NULL;
