USE qa_deo_egov_docker;

ALTER TABLE df_attribute CHANGE id id INT(19) AUTO_INCREMENT NOT NULL;

ALTER TABLE gedo_tipodocumento_familia_aud
 CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL,
 CHANGE ID_FAMILIA ID_FAMILIA INT(19);
