apiVersion: v1
kind: PersistentVolume
metadata:
  name: recursos-mineco
  namespace: mineco
  labels:
    recursos: ready
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
   nfs:
     server: 128.5.105.221
     path: "/deployment/application/recursos"
#  hostPath:
#    path: "/deployment/application/recursos"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recursos-mineco
  namespace: mineco
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      recursos: ready
