
package com.egoveris.trade.ws.fusedemoservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FuseDemoService", targetNamespace = "http://trade.egoveris.com/ws/FuseDemoService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FuseDemoService {


    /**
     * 
     * @param externalRequest
     * @return
     *     returns com.egoveris.trade.ws.fusedemoservice.Acknowledge
     */
    @WebMethod(operationName = "FuseDemoCallback", action = "http://trade.egoveris.com/ws/FuseDemoService/FuseDemoCallback")
    @WebResult(name = "acknowledge", targetNamespace = "")
    @RequestWrapper(localName = "FuseDemoCallback", targetNamespace = "http://trade.egoveris.com/ws/FuseDemoService/", className = "com.egoveris.trade.ws.fusedemoservice.FuseDemoCallback")
    @ResponseWrapper(localName = "FuseDemoCallbackResponse", targetNamespace = "http://trade.egoveris.com/ws/FuseDemoService/", className = "com.egoveris.trade.ws.fusedemoservice.FuseDemoCallbackResponse")
    public Acknowledge fuseDemoCallback(
        @WebParam(name = "externalRequest", targetNamespace = "")
        ExternalRequest externalRequest);

}
