apiVersion: v1
kind: ServiceAccount
metadata:
  name: linea-qa
  namespace: diaco

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-linea
  namespace: nginx-ingress
spec:
  type: LoadBalancer
  externalIPs:
    - 128.5.4.26
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
  selector:
    app: nginx-ingress

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: diaco-pv-pvc-backend
  namespace: diaco
  labels:
    name: diaco-pv-pvc-backend
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 128.5.8.222
    path: "/deployment/qa/diaco/backend"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diaco-pv-pvc-backend
  namespace: diaco
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: diaco-pv-pvc-backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linea-qa
  namespace: diaco
  labels:
    run: linea-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      run: linea-qa
  template:
    metadata:
      labels:
        run: linea-qa
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 128.5.8.26
        searches:
          - diaco-dev.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      containers:
        - name: linea-qa-server
          image: jjolon/lara_vue:2
          resources:
            requests:
              memory: "Gi"
              cpu: "200m"
            limits:
              memory: "3Gi"
              cpu: "700m"
          ports:
            - containerPort: 443
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: "/var/www/html"
              name: vol-php-backend
      volumes:
        - name: vol-php-backend
          persistentVolumeClaim:
            claimName: diaco-pv-pvc-backend

---
apiVersion: v1
kind: Service
metadata:
  name: linea-qa
  namespace: diaco
  labels:
    app.kubernetes.io/name: linea-qa
    app.kubernetes.io/part-of: linea-qa
spec:
  # type: ClusterIP
#  type: NodePort
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: listener-2
      port: 443
      protocol: TCP
  selector:
    run: linea-qa

