apiVersion: v1
kind: ServiceAccount
metadata:
  name: oga-qa
  namespace: mineco-qa

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-oga
  namespace: nginx-ingress
spec:
  type: LoadBalancer
  externalIPs:
    - 128.5.4.43
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
  selector:
    app: nginx-ingress
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: oga-qa
  namespace: mineco-qa
  labels:
    name: oga-qa
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 128.5.8.222
    path: "/deployment/qa/oga"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oga-qa
  namespace: mineco-qa
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: oga-qa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oga-qa
  namespace: mineco-qa
  labels:
    run: oga-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      run: oga-qa
  template:
    metadata:
      labels:
        run: oga-qa
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 128.5.8.26
        searches:
          - mineco-dev-dev.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      containers:
        - name: oga-qa
          image: jjolon/dsnc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: "/var/www/html"
              name: vol-php-oga-qa
      volumes:
        - name: vol-php-oga-qa
          persistentVolumeClaim:
            claimName: oga-qa
---

apiVersion: v1
kind: Service
metadata:
  name: oga-qa
  namespace: mineco-qa
  labels:
    app.kubernetes.io/name: oga-qa
    app.kubernetes.io/part-of: oga-qa
spec:
  type: ClusterIP
  #  type: LoadBalancer
  #  externalIPs:
  #    - 128.5.4.35
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: listener-2
      port: 443
      protocol: TCP
  selector:
    run: oga-qa
