USE qa_te_trade;

ALTER TABLE te_expedient_transaction CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;
ALTER TABLE TE_REGISTRY_TRANSACTION CHANGE ID ID INT(19) AUTO_INCREMENT NOT NULL;


USE qa_deo_trade;

ALTER TABLE gedo_documento ENGINE = MyISAM;