apiVersion: v1
kind: ServiceAccount
metadata:
  name: aseggys
  namespace: mineco
---
# VOLUME DATA
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aseggys-deploy
  namespace: mineco
  labels:
    name: aseggys-deploy
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 128.5.8.222
    path: "/deployment/Site"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aseggys-deploy
  namespace: mineco
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: aseggys-deploy

---
# DEPLOYMENT APP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aseggys
  namespace: mineco
  labels:
    run: aseggys
spec:
  replicas: 1
  selector:
    matchLabels:
      run: aseggys
  template:
    metadata:
      labels:
        run: aseggys
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 128.5.8.26
        searches:
          - mineco-dev.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      containers:
        - name: aseggys
          image: jjolon/ubuntu_03:v1
          # image: jjolon/ubuntu_02:latest
          resources:
            requests:
              memory: "0.5m"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "700m"
          ports:
            - containerPort: 443
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: "/var/www/html"
              name: aseggys-vol
      volumes:
        - name: aseggys-vol
          persistentVolumeClaim:
            claimName: aseggys-deploy

---
apiVersion: v1
kind: Service
metadata:
  name: aseggys
  namespace: mineco
  labels:
    app.kubernetes.io/name: aseggys
    app.kubernetes.io/part-of: aseggys
spec:
  # type: ClusterIP
  type: LoadBalancer
  externalIPs:
    - 128.5.4.24
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: listener-2
      port: 443
      protocol: TCP
  selector:
    run: aseggys
