apiVersion: v1
kind: ServiceAccount
metadata:
  name: farmacia
  namespace: mineco
---
# VOLUME DATA
apiVersion: v1
kind: PersistentVolume
metadata:
  name: farmacia-deploy
  namespace: mineco
  labels:
    name: farmacia-deploy
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 128.5.8.222
    path: "/deployment/farmacia"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: farmacia-deploy
  namespace: mineco
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: farmacia-deploy

---
# DEPLOYMENT APP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmacia
  namespace: mineco
  labels:
    run: farmacia
spec:
  replicas: 1
  selector:
    matchLabels:
      run: farmacia
  template:
    metadata:
      labels:
        run: farmacia
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 128.5.8.26
        searches:
          - mineco-dev.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      containers:
        - name: farmacia
          image: jjolon/assegys:v1
          # image: jjolon/ubuntu_02:latest
          resources:
            requests:
              memory: "0.5m"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "700m"
          ports:
            - containerPort: 443
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: "/var/www/html"
              name: farmacia-vol
      volumes:
        - name: farmacia-vol
          persistentVolumeClaim:
            claimName: farmacia-deploy

---
apiVersion: v1
kind: Service
metadata:
  name: farmacia
  namespace: mineco
  labels:
    app.kubernetes.io/name: farmacia
    app.kubernetes.io/part-of: farmacia
spec:
  # type: ClusterIP
  type: LoadBalancer
  externalIPs:
    - 128.5.4.48
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: listener-2
      port: 443
      protocol: TCP
  selector:
    run: farmacia
