apiVersion: v1
kind: ServiceAccount
metadata:
  name: renap-server
  namespace: mineco
---
# #  INGRESS MINECO
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-ingress-renap
#   namespace: nginx-ingress
# spec:
#   type: LoadBalancer
#   externalIPs:
#   - 128.5.4.22
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#       name: http
#     - protocol: TCP
#       port: 443
#       targetPort: 443
#       name: https
#   selector:
#     app: nginx-ingress

---
# VOLUME DATA
apiVersion: v1
kind: PersistentVolume
metadata:
  name: renap-deploy
  namespace: mineco
  labels:
    name: renap-deploy
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 128.5.8.222
    path: "/deployment/renap-mineco"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renap-deploy
  namespace: mineco
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: renap-deploy

---
# DEPLOYMENT APP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: renap-server
  namespace: mineco
  labels:
    run: renap-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: renap-server
  template:
    metadata:
      labels:
        run: renap-server
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 128.5.8.26
        searches:
          - mineco-dev.svc.cluster.local
          - svc.cluster.local 
          - cluster.local
      containers:
      - name: renap-server
        image: jjolon/php-74:latest
        ports:
          - containerPort: 443
            protocol: TCP
          - containerPort: 80
            protocol: TCP
        volumeMounts:
            - mountPath: "/var/www/html"
              name: vol-php-renap
      volumes:
        - name: vol-php-renap
          persistentVolumeClaim:
            claimName: renap-deploy


---
apiVersion: v1
kind: Service
metadata:
  name: renap-server
  namespace: mineco
  labels:
    app.kubernetes.io/name: renap-server
    app.kubernetes.io/part-of: renap-server
spec:
  # type: ClusterIP
  type: LoadBalancer
  externalIPs:
  - 128.5.4.22
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: listener-2
      port: 443
      protocol: TCP
  selector:
    run: renap-server
