apiVersion: v1
kind: ServiceAccount
metadata:
  name: secretaria-server
  namespace: mineco
---
# VOLUME DATA
apiVersion: v1
kind: PersistentVolume
metadata:
  name: secretaria-deploy
  namespace: mineco
  labels:
    name: secretaria-deploy
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 128.5.8.222
    path: "/deployment/secretaria"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secretaria-deploy
  namespace: mineco
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: secretaria-deploy

---
# DEPLOYMENT APP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretaria-server
  namespace: mineco
  labels:
    run: secretaria-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: secretaria-server
  template:
    metadata:
      labels:
        run: secretaria-server
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 128.5.8.26
        searches:
          - mineco-dev.svc.cluster.local
          - svc.cluster.local 
          - cluster.local
      containers:
      - name: secretaria-server
        image: jjolon/php-full:latest
        ports:
          - containerPort: 443
            protocol: TCP
          - containerPort: 80
            protocol: TCP
        volumeMounts:
            - mountPath: "/var/www/html"
              name: vol-php-sic
      volumes:
        - name: vol-php-sic
          persistentVolumeClaim:
            claimName: secretaria-deploy


---
apiVersion: v1
kind: Service
metadata:
  name: secretaria-server
  namespace: mineco
  labels:
    app.kubernetes.io/name: secretaria-server
    app.kubernetes.io/part-of: secretaria-server
spec:
  type: LoadBalancer
  externalIPs:
  - 128.5.4.51
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: listener-2
      port: 443
      protocol: TCP
  selector:
    run: secretaria-server
