/*
 * <- EDT -> 
 */
DELETE FROM dev_edt_snrsa_g.property_configuration;
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('acronimoPaseEE','PV','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('actEstadoRegistro.cronExpression','0 0 23 1/1 * ? *','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ad.acronimo.paquete.archivo.gedo','ARCHI','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ad.carpeta.raiz.rudo','EXPEDIENTE_ELECTRONICO_ARCHIVADO','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('amq.eu.alertas','eu.notificaciones','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('amq.url','tcp://localhost:61616','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.ccoo.url','http://euc.cap.gde.gob.ar/co-satra-tramita-web','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.co.satra.url','http://euc.cap.gde.gob.ar/co-satra-tramita-web/','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.context_path','eu-web','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.deo.url','http://7.214.8.26:9010/deo-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.deploy.departamento','','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.deploy.localidad','','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.deploy.provincia','','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.ecosistema','APN','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.ecosistema','APN','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.ecosistema','  ','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.ecosistema.label','GDE','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.edt.fromEmail','noreply@egoveris.com','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.ee.url','http://7.214.8.26:9010/te-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.eu.mail.password','gde20161234','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.eu.mail.password','gde20161234','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.eu.mail.user','gde@modernizacion.gob.ar','CCOO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.eu.mail.user','gde@modernizacion.gob.ar','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.eu.mail.user','gde@modernizacion.gob.ar','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.eu.mail.user','gde@modernizacion.gob.ar','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.eu.url','http://7.214.8.26:9000/edt-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.ffdd.url','http://7.214.8.26:9000/ffdd-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.fuse.endpoint.url','http://7.212.8.112:9600/message/send','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.fuse.wsdl.request','http://7.212.8.112:9600/ws/FuseDemoService?wsdl','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.gedo.batch.url','http://7.214.8.26:9010/deo-web','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.gedo.url','http://7.214.8.26:9010/deo-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.loys.url','http://loys-test.gcaba.everis.int:80/loys-satra-tramita-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.mail.ccoo.link','http://euc.cap.gde.gob.ar/ccoo-web/','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.max.preview','3','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.mule.url','http://7.212.8.112:9600','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.mule.url','http://7.212.8.112:9600','MULE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.name','eGoveris','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.nombreModulo','SADE','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.noValidarCcooLogin','12,13,14,15','TRACK');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.numerador.rep.actu.GEDO','APN','NUMERADOR');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.numerador.tiempoRecargaSectores','3600000','NUMERADOR');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.numerador.url','http://7.214.8.26:9030/numerador-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.psoc.url','http://7.214.8.26:9010/deo-web','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.rib.url','http:///rib-web/','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.ric.rmi.url','7.217.8.48','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.ric.url','http://ric-test.gcaba.everis.int/ric-web-man','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.sistema.gestor.documental','WEBDAV','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.te.url','http://7.214.8.26:9010/te-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.ticapdf.algoritmo','SHA-256','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.ticapdf.alias','egoveris','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.ticapdf.keystore','/data/config/ticaconf/certificates/keyStore','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.ticapdf.password','egoveris','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.ticapdf.sello','/data/config/ticaconf/images/sello.png','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.ticapdf.url','http://7.214.8.26:9010/tica-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.track.url','http://eut.cap.gde.gob.ar/sade-satra-tramita-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.url','http://eud.cap.gde.gob.ar/sade-dm-web','DM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.url','http://7.214.8.26:9010/te-web','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.url','http://7.214.8.26:9000/edt-web','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.url','http://7.214.8.26:9000/ffdd-web','FFDD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.url','http://7.214.8.26:9010/deo-web','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.url','http://7.214.8.26:9020/wd-web','WD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('app.vuc.url','http://7.214.8.26:9020/vuc-front-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('arch.enviarAEECarat','1','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('arch.enviarAEEMasivo','0','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('arch.formatoFechaBATCH','dd-MM-yyyy','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('arch.loteCaratulaMasiva','999','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('arch.motivo.Guarda.Temporal','Pase a Guarda Temporal','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('arch.nombreMetadato.trata.electronica','Ex. papel','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('arch.separador.csv','#','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('arch.service.url','http://eua.cap.gde.gob.ar/archivo-web','TRACK');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('arch.solr.rowsnum','1000','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('arch.trata.electronica','GENE3601A','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('arch.url','http://eua.cap.gde.gob.ar/archivo-web','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('arch.usuariosHabilitadosMigracion','EVERIS','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('aud.acronimo.docIndice.auditoria.gedo','AEIPC','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('aud.acronimo.paquete.auditoria.gedo','AEPPA','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('aud.referencia.docIndice.auditoria.gedo','Auditoria de Expediente','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('aud.referencia.paquete.auditoria.gedo','Auditoria de Expediente','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('aud.referencia2.docIndice.auditoria.gedo','Indice parcial de contenidos.','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('aud.referencia2.paquete.auditoria.gedo','Paquete parcial de archivos.','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('aud.tiempo.cierre.actividad','121130','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('baja.usuarioAD.cron','baja','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.archivoDefinitivo.reintentos','5','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.archivoDefinitivo.reintentos','5','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.day.archivoDefinitivo.cron','0 0 19 1/1 * ?','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.day.regExpression','0 0 23 1/1 * ? *','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.day.regExpression','0 0 0/2 1/1 * ? *','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.day.regExpression.EnvioGT','0 0/15 * * * ? *','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.day.regExpression.Migracion','0 0 0-5 * * ?','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.day.regExpression.quartzEnvioDocDepuracion','0 0/20 * * 1/1 ? *','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.dayEE.regExpression','0 0/2 * 1/1 * ? *','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.dep.solicitud.elim.Expression','0 0 12 1 4 ? *','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.dep.solicitud.envio.Expression','0 0 12 1 4 ? *','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.depuracion.asignacion.dias.vencimiento','3000','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.depurar.asignacion.cantidadDeEjecuciones','0','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.depurar.asignacion.regExpression','0 0/15 * 1/1 * ? 2016','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.directory.destination','/tempdigital/destination/final/','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.directory.destinationMigration','/tempdigital/destination/migration','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.directory.finalDestination','/tempdigital/destination/final/','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.directory.source','/tempdigital/temp/','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.directory.sourceDay','/tempdigital/source/day/','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.directory.sourceManual','/tempdigital/temp/','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.directory.sourceMigration','/disco/','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.directory.temp','/tempdigital/temp/','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.directory.tempMigration','/tempdigital/temp','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.inboxGrupal.asig.regExpression','0 0 12 1 1 ? *','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.inboxGrupal.cantidadDiasVencimiento','7','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.server.migracion','CAPGDELXAPPT13','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('batch.server.name.running','CAPGDELXAPPT13','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('cambioMisDatos.descAdicional','-','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('cambioMisDatos.motivoPase','Actualizacion de informacion propia','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('cambioMisDatos.trata','MMOD00000','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('cantMeses.envioAutomaticoGT','1','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('cargoGEDO','','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('cas.url','https://7.214.8.26:9043','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('cas.urlLogOutCAS','https://7.214.8.26:9043/cas/logout','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('cas.wd.url','https://7.214.8.26:9043','WD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('client.id','rlm.client.mq','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('codigoReparticionGEDO','codigoReparticionGEDO','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('config.reparticion.actuacion','APN','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('cron.Migracion.tarea','0 0 12 ? 1/1 MON#4 *','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('cronExpression','0 0 13 * * ?','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('cronExpressionReintentos','0 0/1 * 1/1 * ? *','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('cuentaGA',''UA-46257802-1', 'everis.int'','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('dias.altaDC','1','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('diasBorradoArchivos','1','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('dm.importDocumentos.cronExpression','0 0 1 1/1 * ? *','DM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('dm.importExpedientes.cronExpression','0 0 1 1/1 * ? *','DM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('dm.importExpedientes.dias','360','DM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('dm.responseWaitingTimeout','30000','DM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('dm.sendMails.cronExpression','0 0 1 1/1 * ? *','DM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('dm.sendMails.email','everis@everis.com','DM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('dm.serviceUrl','http://eud.cap.gde.gob.ar/sade-dm-web','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('DMServicioURL','http://eud.cap.gde.gob.ar/sade-dm-web','DM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('dynform.url','http://7.214.8.26:9000/ffdd-web','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('dynform.url','http://7.214.8.26:9000/ffdd-web','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('dynform.url','http://7.214.8.26:9000/ffdd-web','MULE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('dynform.url','http://7.214.8.26:9000/ffdd-web','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('dynform.url','http://7.214.8.26:9000/ffdd-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.acronimo.notificacion','CONOT','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.acronimo.notificacion','CONOT','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.batch.day.regExpression.quartzActividad','0 0 0-23 * * ? *','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.batch.migracion.sistemasNoValidos','LOYS,PSOC','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.batch.regExpression.archivoDefinitivo','40 0/1 * 1/1 * ? *','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.batch.regExpression.archivoDefinitivo','40 0/1 * 1/1 * ? *','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.cantidad.de.dias.en.guarda.temporal','730','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.cargos.archivodefinitivo','Jefe de gobierno,Vicejefe de gobierno,Secretario,Subsecretario,Jefe de gabinete de ministros,Director general','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.consulta.bd','false','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.cronCargaFeriados','0 0 0 * * ?','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.jms.servidor','tcp://amq.cap.gde.gob.ar:61616','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.jms.servidor','tcp://7.217.8.23:61616','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.mail.subsanacion.documentos','capac_sindicatura@buenosaires.gob.ar','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.permanencia.en.guarda.param.visible','0','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.plugin','file:///opt/versions/PluginManager/ee','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.plugin_webdav','/PluginManager/ee/deployegovdocker','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.reparticion.GT','APN','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.reparticion.tiempo','900000','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.sectorinterno.tiempo','14400000','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.service.url','http://7.214.8.26:9010/te-web','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.serviceUrl','http://7.214.8.26:9010/te-web','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.sistemasArchivadores','ARCH,LOyS','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.sistemasExternos','PSOC,LOYS,SGAint,Fisca,SGI-PG,TTRE,Ley257,SISTEMA,Sistema,SGAI,DGSUM,ARCH,matriz de riesgo,SAGI,LEY257,SAP,APRA_P060_CD2,SIGAFPL,EE,KODAK,CEP,SADE,SAPCRM,SGI,SGIPG,SIGAF_WEB,TAD,BAC,LEY 257,SIGAF,DIGESTO,matriz,','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.smtp.from','escritorio.unico@egoveris.com','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.smtp.host','','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.smtp.port','25','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.smtp.username','escritorio.unico','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.TomaVistaAceptacion.Acronimo','IFTVA','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.TomaVistaRechazo.Acronimo','IFTVR','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.TomaVistaSinSuspension.Acronimo','COTVI','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.trata.tiempo','900000','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.tratas','GENE0103A,MEGC0107A,ACER00004,GENE0301A,GENE0302A,GENE0303A,GENE0307A,GENE0308A,GENE0309A,GENE0312A,GENE0314A,MMGC0101A,GENE0313A,GENE0315A,GENE0316A,MHGC 0112B,MHGC 0112C,MEGC0107A,MHGC0106A ,MHGC0113A,GENE0310A','DM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.tratasDeRemision','SADE8,GENE1507A','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.trataTomaVista','GENE2503A','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.url','http://7.214.8.26:9010/te-web','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.url','http://7.214.8.26:9010/te-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.user.tomaVista','EVERIS','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ee.usuario.tiempo','18000000','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('envioCorreoActivo','false','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('eu.estructura.ministerio','1,2,4,5','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('eu.refresco_modulo_reparticiones','900000','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('eu.rep.default.ministerio.presupuesto','','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('eu.tiempo_refresco_tareas','300000','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('eu.url','http://7.214.8.26:9000/edt-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('eu.usu.nombres_prohibidos','TEST,PRUEBA,CONSULTA,CAPACITACION','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('EUServicioURL','http://7.214.8.26:9000/edt-web','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('fileNet.nombre.modulo','EE','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('flag.crear.tramite','1','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('fullimportUsuarios.cronExpression','0 0/18 * 1/1 * ? *','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.activacionDepuracionDocumento','false','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.activacionDepuracionDocumento.cron','0 0 1 1/1 * ? *','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.ambienteDesa','true','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.archivos.embebidos.tamanio.maximo','2048000','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.cantidadReintentosNotificacion','5','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.chequearTSASiempre','false','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.deltaimport.cron','0 0/5 * 1/1 * ?','GEDO.N1');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.deltaimport.cron','0 0 12 1 1 ?','GEDO.N2');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.deltaimport.cron','0 0 12 1 1 ?','GEDO.N3');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.deltaimport.cron','0 0 12 1 1 ?','GEDO.N4');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.deltaimport.cron','0 0 12 1 1 ?','GEDO.N5');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.deltaimport.cron','0 0 12 1 1 ?','GEDO.N6');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.deltaimport.cron','0 0 12 1 1 ?','GEDO.N7');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.deltaimport.cron','0 0 12 1 1 ?','GEDO.N8');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.deltaimport.cron','0 0 12 1 1 ?','GEDO.N9');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.leyendaConmemorativa','Versión de Desarrollo','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.limpiezaTemporales.activacionAvisoMail','false','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.limpiezaTemporales.activacionProcesoLimpieza','false','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.limpiezaTemporales.cantidadMesesLimpieza','3','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.limpiezaTemporales.cronAvisoMail','0 0 0 12 * ?','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.limpiezaTemporales.cronProcesoLimpieza','0 0 0 19 * ?','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.limpiezaTemporales.diferenciaDeDiasEntreMailYLimpieza','7','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.maximoArchivos','1000','DM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.maximoArchivos','2048000','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.maximoArchivos','102400','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.maximoPrevisualizacion','1000','DM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.maximoPrevisualizacion','10240','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.maximoPrevisualizacion','20480','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.medicion.acronimo','IF','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.medicion.contenido','<p>Este es un documento de prueba para medir tiempos en el proceso de firma</p>','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.medicion.formato','XML','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.medicion.referencia','Prueba para medir tiempos','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.medicion.tipoContenido','html','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.medicion.usuario','EVERIS','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.path_template_recibo','D:\\Adobe\\Templates Recibo Sueldo','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.properties.cron','0 0 12 1/1 * ? *','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.reparticion.tiempo','900000','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.serviceUrl','http://7.214.8.26:9010/deo-web','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.tiempoReintentoConfiguracion','7200','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.url','http://7.214.8.26:9010/deo-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.usuario.tiempo','900000','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('gedo.verificarTSa.cron','*/30 * * * * ?','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('generic.repa.autom','LOYS','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('generic.usuario.autom','MCURUTCHET','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('host.deo','http://7.214.8.26:9010/deo-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('host.edt','http://7.214.8.26:9000/edt-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('host.ffdd','http://7.214.8.26:9000/ffdd-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('host.te','http://7.214.8.26:9010/te-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('host.wd','http://7.214.8.26:9020/wd-web','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('id.tramites.escribanos','1,177,300,305','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('jbpm.cantidadReintentos','20','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('jms.nombre','EE.datos.topic','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('jms.nombre','prueba','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('jms.timeOut','30000','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('jms.url','tcp://amq.cap.gde.gob.ar:61616','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('jms.urlQueue','tcp://amq.cap.gde.gob.ar:61616','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('jms.urlTopic','tcp://amq.cap.gde.gob.ar:61616','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('job.limpiezaTemoralesFFDD','0 0/1 * 1/1 * ?','FFDD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('label.solicitud.copia.digital','','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ldap.admin.password','password','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ldap.admin.password.ad','','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ldap.admin.user','cn=Manager,DC=egoveris,DC=com','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ldap.admin.user.ad','','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ldap.base','DC=egoveris,DC=com','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ldap.base.ad','','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ldap.entorno','SADE','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ldap.ou','funcionarios','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ldap.ou.base','ou=funcionarios','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ldap.url','ldap://7.214.8.26:389','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ldap.url.ad','','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ldap.user.account.control.ad','cn=Manager,DC=egoveris,DC=com','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ldapUrlAD','','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('le.responseWaitingTimeout','30000','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('ley104.motivoPase','Motivo pase a funcionario público','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('limiteDiasExpedienteReintentos','3','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('logo','egov','FFDD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('lue.serviceUrl','http:///le-web/','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('lue.url','http:///le-web','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('mailsReintentos','reintentos@egoveris.com','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('maxOcurrenciasDoc','100','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('mensajeEmbebido','Documento Embebido TAD','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('migracion.modulo','EE','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('migracion.modulo','EU','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('migracion.modulo','GEDO','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('migracion.modulo','RLM','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('migracion.modulo','TRACK','TRACK');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('migracion.tarea.cronExp','0 6-21,36-51 * * * ?','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('migracion.tarea.cronExp','0-59 1-59 * * * ?','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('migracion.tarea.cronExp','0 1/1 21,22,23,01,02,03,04,05,06 * * ?','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('migracion.tarea.cronExp','0 0/5 * 1/1 * ? *','TRACK');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('migracion.tarea.cronExp2','0-59 1-59 * * * ?','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('migracion.tarea.cronExp2','0 1/1 21,22,23,01,02,03,04,05,06 * * ?','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('migracion.usuariosTareas','*','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('modulo.name.guarda.documental','GEDO','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('mule.url','','SISTEMA.MULE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('nombre.ecosistema','GDE','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('nombre.entorno','ee','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('nombre.host.migracion','EE_01','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('nombre.host.migracion','sade-test-ws1','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('nombre.host.migracion','gedo1','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('nombre.host.migracion','RLM_SADE-PRD','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('nombre.servidor.baja.AD','baja','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('nombre.sistema','GDE','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('novedades.cronExpression','0 0 6 1/1 * ?','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('numerador.proceso.cantidadPorInvocacion','500','NUMERADOR');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('numerador.proceso.cron','0 0 0 * * ?','NUMERADOR');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('numerador.proceso.reintento','3','NUMERADOR');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('numero.esp.electronico','true','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('password.citas','ZDNmNGg2ajc=','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('permisoAsignador','ou=ee.asignador,ou=grupos,dc=gob,dc=ar','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('psoc.url','http:///psoc-web/','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('qrtz.prefix','QRTZ_','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('qrtz.prefix','QRTZCO_','SISTEMA.CCOO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('renaperConsulta.ws.url','http://wsf.cdyne.com/WeatherWS/Weather.asmx','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('renaperConsulta.ws.url.testeo','http://wsf.cdyne.com/WeatherWS/Weather.asmx','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('renaperFallecimientos.ws.url','http://wsf.cdyne.com/WeatherWS/Weather.asmx','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('renaperFallecimientos.ws.url.testeo','http://wsf.cdyne.com/WeatherWS/Weather.asmx','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('renaperRegistrarPersonaSinDocumento.ws.url','http://wsf.cdyne.com/WeatherWS/Weather.asmx','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('renaperRegistrarPersonaSinDocumento.ws.url.testeo','http://wsf.cdyne.com/WeatherWS/Weather.asmx','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('reparticion.actuacion','APN','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('reparticion.actuacion','APN','TRACK');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('reparticion.actuacion_id','2100000','TRACK');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('reparticion.rrhh','SUBRH','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('reparticiones.tiempo','900000','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('repository.connectionTimeout','15000','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('repository.defaultPassword','admin','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('repository.defaultUsername','admin','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('repository.documentRoot','/guarda-documental','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('repository.hostname','7.214.8.26','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('repository.port','80','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('rib.url','http:///rib-web/panelBusqueda.zul','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('rlm.motivoActualizacion','Actualizacion automatica de registros','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('rlm.reparticion.sector.tiempo','9000000','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('rlm.reparticiones.tiempo','9000000','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('rlm.reparticionValidadora','APN','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('rlm.usuarioActualizacion','RLMAutomatico','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('rlm.usuarios.tiempo','9000000','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('RPA.aniosMatricula','2010','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('rpaadm.desccarat','ADMINISTRADOR INSCRIPTO MATRICULA Nº','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('rpacon.desccarat','INFORMACION CORRESPONDIENTE A CADA CONSORCIO ADMINISTRADO','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('rup.serviceUrl','http:///gup-web/','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('rutaTemporales','','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sade.jmsUrl','tcp://amq.cap.gde.gob.ar:61616','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('security.usuarios.refrescoMinutos','5','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.acronimo.pv','PV','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.contador.archivo.definitivo','25280','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.contenido.pv.ad','Motivo:','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.edifElectro.archivarEE','Edificio central','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.gedoAcronimo','COPDI','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.gedoMotivo','DIGITALIZER','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.gedoUsuario','MIDELMAZO','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('SGA.INYcantDiasPermanencia','14600','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('SGA.INYedificioDefault','Edificio central','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('SGA.INYobservaciones','Expediente Inyectado desde Arch','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('SGA.INYsedeDefault','1','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.lote','5','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.lote.archivo.definitivo','18000','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.lotes','5','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.maximo.archivar','5000','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.Mensaje.ad.digi.err','El expediente no puede ser digitalizado ni generar copiaDigital, ya que es de Origen Electronico','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.motivo.FIJO','Pase electronico de','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.motivo.variable','false','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.motivoPase.archivarEE','Pase electronico Solicitud Archivo','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.nodo.archivo.definitivo','CAPGDELXAPPT12','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.referencia.paquete.AD','Paquete Electronico Archivo','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.rol.admin','SA.ADMIN','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.rol.archivador','SA.ARCHIVADOR','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.rol.CentroDigital','SA.CENTRODIGITAL','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.rol.consulta','SA.CONSULTA','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.rol.editar.caja','SA.ADMIN.CAJAS','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.rol.Metadatos','SA.METADATOS','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.tamanio.archivo.manual','100','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('sga.total.archivo.definitivo','21250','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('siga.satra.url','http://','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.activarIndexacion','1','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.activarIndexacion','true','TRACK');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.arch.connectionTimeout','6000','TRACK');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.arch.maxConnectionsPerHost','100','TRACK');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.arch.maxTotalConnections','100','TRACK');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.arch.url','http://7.214.8.26:8092/bweb-solr/core-arch','TRACK');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.ccoo.connectionTimeout','1000','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.ccoo.maxConnectionsPerHost','1000','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.ccoo.url','http://7.214.8.26:8092/bweb-solr/core-ccoo','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.connectionTimeout','1000','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.connectionTimeout','6000','TRACK');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.cooo.maxTotalConnections','100','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.ee.maxConnPerHost','1000','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.ee.maxtotalConn','1000','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.ee.timeout','1000','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.ee.url','http://7.214.8.26:8092/bweb-solr/core-ee','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.eeCoreName','core-ee','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.eu.url','http://7.214.8.26:8092/bweb-solr/core-eu','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.euCoreName','core-eu','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.gedoCore.url','http://7.214.8.26:8092/bweb-solr/coreGEDO','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.maxConnectionsPerHost','1000','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.maxConnectionsPerHost','100','TRACK');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.maxTotalConnections','100','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.rlm.url','http://7.214.8.26:8092/bweb-solr/coreRLM','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.rlmCoreName','coreRLM','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.track.url','http://7.214.8.26:8092/bweb-solr/core-track','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.url','http://7.214.8.26:8092/bweb-solr/core-arch','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.url','http://7.214.8.26:8092/bweb-solr/core-track','TRACK');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solr.usr.url','http://7.214.8.26:8092/bweb-solr/coreUSUARIOS','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solrServerTrack.activarIndexacion','false','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solrServerTrack.connectionTimeout','6000','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solrServerTrack.maxConnectionsPerHost','100','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solrServerTrack.maxTotalConnections','100','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('solrServerTrack.url','http://7.214.8.26:8092/bweb-solr/core-track','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('tad.ecosistema','APN','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('tad.mailMesaAyuda','sjaboss@gmail.com','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('tad.url','http://7.214.8.26:9030','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('tareas.busqueda.tiempo','6','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('tiempo.recarga.rep.usu','900000','SGA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('tipoCCOO.memo','MEMO','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('tipoCCOO.nota','NOTA','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('tipoDocCache.refresh.ms','900000','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('tipoDocCache.refresh.ms','3000','WD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('tipoDocumentoApoderado','COAPO','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('tituloDocumentoCaratulaVariable','Datos Adicionales para la Caratula','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('topic.id','tcp://amq.cap.gde.gob.ar:61616','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('topic.name','EE.datos.topic','RLM');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('tsa.url','','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('url.archivo.logo','SADE','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('url.filenet','http://--------------------/filenetservice/?wsdl','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('user.citas','tad','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('usuario.envioAutomaticoGT','DOMINGUEZRE','EE');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('validarfirma.connectiontimeout','60000','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('validarfirma.readtimeout','10000','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('validarfirma.soap.url','http://livecycle.cap.gde.gob.ar/soap/services/ValidarFirmas','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('validarTipoDocumento.firmaConjunta','ANDEC;ANEDE;DECRE;DECTO;PRODE','GEDO');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('webdav.connectionTimeout','15000','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('webdav.defaultPassword','admin','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('webdav.defaultPassword','sade','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('webdav.defaultUsername','admin','EU');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('webdav.defaultUsername','sade','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('webdav.documentRoot','/guarda-documental/','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('webdav.hostName','7.214.8.26','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('webdav.port','10080','SISTEMA');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('wsdl.agip','https://desa.agip.gob.ar/claveciudad/claveCiudadWS','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('wsdl.citas','http://desa.egoveris.com:8880/apps/api-citas-hml/ws.citas.php','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('wsdl.DC','http://desa.egoveris.com:8088/mock','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('wsdl.DC.decodingXml','UTF-8','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('wsdl.DC.encodingXml','ISO-8859-1','TAD');
INSERT INTO dev_edt_snrsa_g.property_configuration VALUES ('wsdl.DC.externalURL','http://desa.egoveris.com/wsDGDyPC/','TAD');


/*
 * <- MNT -> 
 */
DELETE FROM dev_mnt_snrsa_g.property_configuration;
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('app.url','http://7.214.8.26:9020/mantenedores-web/','MNT');
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('cas.url','https://7.214.8.26:9043','SISTEMA');
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('ldap.admin.password,password,SISTEMA','password','SISTEMA');
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('ldap.admin.password.ad','','SISTEMA');
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('ldap.admin.user','cn=Manager,DC=egoveris,DC=com','SISTEMA');
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('ldap.admin.user.ad','','SISTEMA');
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('ldap.base','DC=egoveris,DC=com','SISTEMA');
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('ldap.base.ad','','SISTEMA');
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('ldap.entorno','SADE','SISTEMA');
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('ldap.ou','funcionarios','SISTEMA');
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('ldap.ou.base','ou=funcionarios','SISTEMA');
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('ldap.url','ldap://7.214.8.26:389','SISTEMA');
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('ldap.url.ad','','SISTEMA');
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('ldap.user.account.control.ad','cn=Manager,DC=egoveris,DC=com','SISTEMA');
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('security.usuarios.refrescoMinutos','5','SISTEMA');
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('solr.maxTotalConnections','100','SISTEMA');
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('solr.track.url','http://7.214.8.26:8092/bweb-solr/core-track','SISTEMA');
INSERT INTO dev_mnt_snrsa_g.property_configuration VALUES ('solr.usr.url','http://7.214.8.26:8092/bweb-solr/coreUSUARIOS','SISTEMA');


/*
 * <- NUMERADOR ->
 */
DELETE FROM dev_numerador_snrsa_g.property_configuration;
INSERT INTO dev_numerador_snrsa_g.property_configuration VALUES ('app.numerador.rep.actu.GEDO','EGOV','SISTEMA');
INSERT INTO dev_numerador_snrsa_g.property_configuration VALUES ('app.numerador.tiempoRecargaSectores','3600000','SISTEMA');
INSERT INTO dev_numerador_snrsa_g.property_configuration VALUES ('numerador.proceso.cantidadPorInvocacion','500','NUMERADOR');
INSERT INTO dev_numerador_snrsa_g.property_configuration VALUES ('numerador.proceso.cron','0 0 0 * * ?','NUMERADOR');
INSERT INTO dev_numerador_snrsa_g.property_configuration VALUES ('numerador.proceso.reintento','3','NUMERADOR');


/*
 * <- TE -> 
 */
DELETE FROM dev_te_snrsa_g.property_configuration;
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('acronimoPaseEE','PV','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.deo.url','http://7.214.8.26:9010/deo-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.deploy.departamento','','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.deploy.localidad','','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.deploy.provincia','','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.ecosistema','  ','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.ee.url','http://7.214.8.26:9010/te-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.eu.mail.password','','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.eu.mail.user','','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.eu.url','http://7.214.8.26:9000/edt-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.ffdd.url','http://7.214.8.26:9000/ffdd-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.fuse.demo.url','rmi://7.212.8.112:9600/sendDemo','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.fuse.endpoint.url','http://7.212.8.112:9600/message/send','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.fuse.wsdl.request','http://7.212.8.112:9600/ws/FuseDemoService?wsdl','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.numerador.url','http://7.214.8.26:9030/numerador-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.sistema.gestor.documental','WEBDAV','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.track.url','aaaa','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.url','http://7.214.8.26:9010/te-web','EE');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.url','http://7.214.8.26:9010/te-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('app.vuc.url','http://7.214.8.26:9020/vuc-front-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('arch.url','http://arch-test.gcaba.everis.int/archivo-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('batch.archivoDefinitivo.reintentos','5','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('batch.day.regExpression','0 0 12 1 1 ? 2018','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('batch.day.regExpression.EnvioGT','0 0/5 * 1/1 * ? 2018','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('batch.day.regExpression.Migracion','0 0/5 * 1/1 * ? 2018','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('batch.day.regExpression.quartzEnvioDocDepuracion','0 0/5 * 1/1 * ? 2018','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('batch.dep.solicitud.elim.Expression','0 2 * 1/1 * ? 2018','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('batch.dep.solicitud.envio.Expression','0 2 * 1/1 * ? 2018','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('batch.depuracion.asignacion.dias.vencimiento','15','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('batch.depurar.asignacion.cantidadDeEjecuciones','2128','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('batch.inboxGrupal.asig.regExpression','0 0 12 1 1 ? 2018','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('batch.inboxGrupal.cantidadDiasVencimiento','7','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('batch.server.migracion','gedo-test-ws1.gcaba.everis.int','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('batch.server.name.running','gedo-test-ws1.gcaba.everis.int??','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('cantMeses.envioAutomaticoGT','6','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('cas.url','https://7.214.8.26:9043','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('dyn','','0');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('dynform.url','http://7.214.8.26:/ffdd-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.acronimo.notificacion','NOTVU','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.bac.tratasHabilitadas','GENE0301A,GENE0302A,GENE0303A,GENE0303B,GENE0307A,GENE0308A,GENE2601A','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.batch.day.regExpression.quartzActividad','0 0/5 * 1/1 * ? 2018','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.batch.migracion.sistemasNoValidos','LOyS,PSOC','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.batch.regExpression.archivoDefinitivo','40 0/1 * 1/1 * ? 2018','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.cargos.archivodefinitivo','Jefe de gobierno,Vicejefe de gobierno,Secretario,Subsecretario,Jefe de gabinete de ministros,Director general','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.consulta.bd','false','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.cronCargaFeriados','0 0 0 * * ?','EE');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.cronCargaFeriados','0 0 0 * * ?','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.envioCorreoActivo','false','EE');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.gedoUrl','http://7.214.8.26:9010/deo-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.jms.servidor','tcp://7.217.8.23:61616','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.mail.subsanacion.documentos','dpadua@everis.com','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.plugin','file:///opt/versions/PluginManager/ee','EE.GUILLE');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.plugin','PluginManager/ee/deployegovdocker','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.plugin_webdav','MGEYA','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.reparticion.GT','900000','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.reparticion.tiempo','30000','EE');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.reparticion.tiempo','900000','EE.AL');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.reparticion.tiempo','MGEYA','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.reparticionesValidas','var mensaje=function(e){throw new Error('MSG: '+e)},cerrarVentana=function(e){esWS()||state.closeWindow(e)},mensajeOK=function(e){esWS()?print(e):state.newMessageOK(e)},mensajeERROR=function(e){esWS()?print(e):state.newErrorMessage(e)},sistemaCreador=function(){return ee.getSistemaCreador()},sistemaApoderado=function(){return ee.getSistemaApoderado()},esWS=function(){return'undefined'!=typeof __isWebService__},invokeRemoteService=function(e,t,n){remoteRestService.invokeRemoteService(e,t,ee,idTransactionFFCC,nameFFCC,n)},blockExpedient=function(){remoteRestService.blockExpedient(ee)},validateStructure=function(e){return remoteRestService.validateStructureForm(e,Form)},initSubProcess=function(e){return remoteRestService.initSubprocess(ee,e)};','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.script.subprocessGeneric','900000','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.sectorinterno.tiempo','900000','EE');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.sectorinterno.tiempo','ARCH,LOyS','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.sistemasArchivadores','BAC,SGI-PG,TTRE,SGAI,LEY257,matriz de riesgo,SAPCRM,SGIPG,SGI,SIGAF_WEB,Policia Metropolitana GAP','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.sistemasExternos','TAD,ARCH,EE','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.sistValidosDeConsultaBuzon','comunicaciones_oficiales@buenosaires.gob.ar','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.smtp.from','7214105112','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.smtp.host','1250','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.smtp.port','egoveris','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.smtp.username','SS81','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.tipoDocCCOO.tomaVista','IFTVA','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.TomaVistaAceptacion.Acronimo','IFTVR','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.TomaVistaRechazo.Acronimo','COTVI','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.TomaVistaSinSuspension.Acronimo','300000','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.trata.tiempo','300000','EE');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.trata.tiempo','300000','EEE');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.trata.tiempo','SADE8,GENE1507A,AGC00503A','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.tratasDeRemision','ACER00004','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.trataTomaVista','http://7.214.8.26:9010/te-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.url','GCABADGM','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.user.tomaVista','18000000','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.usuario.tiempo','18000000','EE');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ee.usuario.tiempo','http://7.214.8.26:9000/edt-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('eu.url','http://7.214.8.26:9000/edt-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('EUServicioURL','EE','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('fileNet.nombre.modulo','1','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('flag.crear.tramite','http://7.214.8.26:9010/deo-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('gedo.url','1','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('GENERAR_DOC_PASE','http://7.214.8.26:9010/deo-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('host.deo','http://7.214.8.26:9000/edt-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('host.edt','http://7.214.8.26:/ffdd-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('host.ffdd','http://7.214.8.26:9010/te-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('host.te','http://7.214.8.26:9020/wd-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('host.wd','prueba','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('jms.nombre','30000','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('jms.timeOut','tcp://7.217.8.23:61616','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('jms.url','<<passwd>>a8naX+PA5LC3zhWVBZGUCfCBrtsTa8/00WvIg5aHZG4=','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('karin.password','password','KARIN');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ldap.admin.password','cn=Manager,DC=egoveris,DC=com','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ldap.admin.user','DC=egoveris,DC=com','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ldap.base','funcionarios','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ldap.ou','ou=funcionarios','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ldap.ou.base','ldap://7.214.8.26:389','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('ldap.url','password','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('livecycle.password','http://livecycle.trade.com:8080','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('livecycle.url.service','administrator','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('livecycle.username','http://rib-test.gcaba.everis.int/le-web','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('lue.url','EE','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('migracion.modulo','0-59 1-59 * * * ?','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('migracion.tarea.cronExp','0-59 1-59 * * * ?','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('migracion.tarea.cronExp2','*','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('migracion.usuariosTareas','http://7.212.8.112:9600','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('mule.url','testepp-www.nic.ar','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('nic.HostName','700','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('nic.HostPort','/opt/versions/epp/nicArTrustCert.jks','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('nic.KeyStoreFileLocation','changeit','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('nic.KeyStorePassword','TestEveris123','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('nic.PassWord','Everis','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('nic.UserName','GDE','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('nombre.ecosistema','ee','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('nombre.entorno','gedo-test-ws1.gcaba.everis.int','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('nombre.host.migracion','EGOV','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('reparticion.actuacion','15000','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('repository.connectionTimeout','admin','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('repository.defaultPassword','admin','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('repository.defaultUsername','/guarda-documental','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('repository.documentRoot','7.214.8.26','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('repository.hostname','80','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('repository.port','BUENO','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('resultado','http://afjg-ee-test.gcaba.everis.int','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('sade.satra.url','5','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('security.usuarios.refrescoMinutos','http://afjg-ee-test.gcaba.everis.int','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('siga.satra.url','1000','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('solr.ee.maxConnPerHost','1000','EE');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('solr.ee.maxConnPerHost','1000','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('solr.ee.maxtotalConn','1000','EE');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('solr.ee.maxtotalConn','1000','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('solr.ee.timeout','1000','EE');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('solr.ee.timeout','http://7.214.8.26:8092/bweb-solr/core-ee','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('solr.ee.url','core-ee','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('solr.eeCoreName','http://7.214.8.26:8092/bweb-solr/coreUSUARIOS','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('solr.usr.url','http://7.214.8.26:8092/bweb-solr/coreUSUARIOS','RLM');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('solr.usr.url','false','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('solrServerTrack.activarIndexacion','6000','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('solrServerTrack.connectionTimeout','100','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('solrServerTrack.maxConnectionsPerHost','100','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('solrServerTrack.maxTotalConnections','http://7.214.8.26:8092/bweb-solr/core-track','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('solrServerTrack.url','http://7.212.8.112:9600','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('tad.url','MEMO','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('tipoCCOO.memo','NOTA','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('tipoCCOO.nota','30000','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('tipoDocCache.refresh.ms','30000','EE');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('tipoDocCache.refresh.ms','OK','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('tipoResultado.1','NOK','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('tipoResultado.2','DOMINGUEZRE','SISTEMA');
INSERT INTO dev_te_snrsa_g.property_configuration VALUES ('usuario.envioAutomaticoGT','DOMINGUEZRE','SISTEMA');


/*
 * <- VUC -> 
 */
DELETE FROM dev_vuc_snrsa_g.property_configuration;
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('app.deo.url','http://7.214.8.26:9010/deo-web','SISTEMA');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('app.ee.url','http://7.214.8.26:9010/te-web','SISTEMA');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('app.ffdd.url','http://7.214.8.26:9000/ffdd-web','SISTEMA');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('app.vuc.url','http://7.214.8.26:9020/vuc-front-web','SISTEMA');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('cambioMisDatos.descAdicional','- ','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('cambioMisDatos.motivoPase','Actualizacion de informacion propia','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('cambioMisDatos.trata','MGOB0123A','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('cargoGEDO',' ','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('codigoReparticionGEDO','codigoReparticionGEDO','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('cronExpression','0 0 1 1/1 * ? *','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('cronExpressionReintentos','0 0 1 1/1 * ? 2099','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('dias.altaDC','1','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('diasBorradoArchivos','1','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('dynform.url','http://7.214.8.26:9000/ffdd-web','SISTEMA');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('envioCorreoActivo','false','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('id.tramites.escribanos','1,177,300,305','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('ley104.motivoPase','Motivo pase a funcionario público','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('limiteDiasExpedienteReintentos','0','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('mailsReintentos','guillermo.gefaell.valcarce@everis.com','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('mensajeEmbebido','Documento Embebido TAD','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('password.citas','ZDNmNGg2ajc=','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('repository.connectionTimeout','15000','SISTEMA');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('repository.defaultPassword','admin','SISTEMA');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('repository.defaultUsername','admin','SISTEMA');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('repository.documentRoot','/guarda-documental','SISTEMA');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('repository.hostname','7.214.8.26','SISTEMA');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('repository.port','80','SISTEMA');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('RPA.aniosMatricula','2010','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('rpaadm.desccarat','ADMINISTRADOR INSCRIPTO MATRICULA Nº ','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('rpacon.desccarat','INFORMACIÓN CORRESPONDIENTE A CADA CONSORCIO ADMINISTRADO','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('rutaTemporales','temporalDocuments','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('tad.mailMesaAyuda','darkkonum@gmail.com','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('tipoDocumentoApoderado','GEAP','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('tituloDocumentoCaratulaVariable','Datos Adicionales para la Caratula','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('url.tad','https://desa.agip.gob.ar/claveciudad/','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('user.citas','tad','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('wsdl.agip','https://desa.agip.gob.ar/claveciudad/claveCiudadWS','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('wsdl.citas','http://localhost:8880/apps/api-citas-hml/ws.citas.php','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('wsdl.DC','http://localhost:8088/mock','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('wsdl.DC.decodingXml','UTF-8','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('wsdl.DC.encodingXml','ISO-8859-1','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('wsdl.DC.externalURL','http://localhost/wsDGDyPC/','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('wsdl.escribanos','http://testing.colegio-escribanos.org.ar:1010/BoraWS/ValidadorMatricula','TAD');
INSERT INTO dev_vuc_snrsa_g.property_configuration VALUES ('wsdl.escribanos','https://servicios.colegio-escribanos.org.ar:8444/BoraWS/ValidadorMatricula','TAD.MM_yaNo');
