insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (724,'admin.ffcc',null,'Permite el acceso al administrador de Formularios Controlados ','FFDD');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (490,'ou=te.adm.tipooper,ou=grupos,dc=egoveris,dc=com',null,'Acceso a la funcionalidad de Administración de Tipo de Operaciones','TE');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (1172,'ou=DEO.TAREAS.MISTAREAS,ou=grupos,dc=egoveris,dc=com','','Acceso Tareas DEO','DEO');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (489,'ou=te.adm.tramites,ou=grupos,dc=egoveris,dc=com',null,'Acceso a la funcionalidad de Administración de Tipo de Trámites','TE');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (482,'ou=te.operaciones,ou=grupos,dc=egoveris,dc=com',null,'Acceso a la funcionalidad de Operaciones','TE');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (483,'ou=te.tareas.mistareas,ou=grupos,dc=egoveris,dc=com',null,'Acceso a la funcionalidad de Mis Tareas','TE');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (484,'ou=te.tareas.buzongrupal,ou=grupos,dc=egoveris,dc=com',null,'Acceso a la funcionalidad de Buzón Grupal','TE');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (485,'ou=te.tareas.supervisados,ou=grupos,dc=egoveris,dc=com',null,'Acceso a la funcionalidad de Supervisados','TE');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (486,'ou=te.consultas,ou=grupos,dc=egoveris,dc=com',null,'Acceso a la funcionalidad de Consultas','TE');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (487,'ou=te.rehabilitar,ou=grupos,dc=egoveris,dc=com',null,'Acceso a la funcionalidad de Rehabilitar Expedientes','TE');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (1173,'ou=DEO.TAREAS.SUPERVISADAS,ou=grupos,dc=egoveris,dc=com','','Acceso Tareas Supervisadas DEO','DEO');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (1171,'ou=edt,ou=grupos,dc=gob,dc=ar',null,'Permiso a EDT','EDT');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (1174,'ou=DEO.CONSULTAS,ou=grupos,dc=egoveris,dc=com','','Acceso a consultas DEO','DEO');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (1175,'ou=DEO.MIS.PLANTILLAS,ou=grupos,dc=egoveris,dc=com','','Acceso a plantillas DEO','DEO');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (1176,'ou=wd.stateflow,ou=grupos,dc=egoveris,dc=com','','Acceso al diseñador de estados','WD');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (1177,'ou=WD.TASKFLOW,ou=grupos,dc=egoveris,dc=com','','Acceso al diseñador de tareas','WD');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (1178,'ou=deo.admin.documentos,ou=grupos,dc=egoveris,dc=com',null,'Acceso Adm Documentos','DEO');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (1179,'ffdd',null,'Acceso a Formularios Dinamicos','FFDD');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (1180,'ou=te.herramientas,ou=grupos,dc=egoveris,dc=com',null,'Acceso a la funcionalidad Herramientas','TE');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (1181,'ou=te.operaciones,ou=te.tareas.mistareas,ou=te.tareas.buzongrupal,dc=gob,dc=ar',null,'Administrador de reglas y tareas','TE');
insert into qa_edt_snrsa_g.adminsade_permisos(ID,PERMISO,ROL,DESCRIPCION,SISTEMA) values (586,'ou=admin.central,ou=grupos,dc=gob,dc=ar','','Administrador central','EGOVERIS');
