apiVersion: v1
kind: ServiceAccount
metadata:
  name: bpm-disercomi
  namespace: mineco-qa

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-ingress-bpm
#   namespace: nginx-ingress
# spec:
#   type: LoadBalancer
#   externalIPs:
#     - 128.5.4.28
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#       name: http
#     - protocol: TCP
#       port: 443
#       targetPort: 443
#       name: https
#   selector:
#     app: nginx-ingress

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: disercomi-pv-pvc-backend
#   namespace: mineco
#   labels:
#     name: disercomi-pv-pvc-backend
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 20Gi
#   accessModes:
#     - ReadWriteOnce
#   nfs:
#     server: 128.5.8.222
#     path: "/deployment/disercomi/backend"


# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: disercomi-pv-pvc-backend
#   namespace: mineco
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
#   selector:
#     matchLabels:
#       name: disercomi-pv-pvc-backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpm-disercomi-server
  namespace: mineco-qa
  labels:
    run: bpm-disercomi-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bpm-disercomi-server
  template:
    metadata:
      labels:
        run: bpm-disercomi-server
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 128.5.8.26
        searches:
          - mineco-dev.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      containers:
        - name: bpm-disercomi-server
          image: jjolon/flowable-ui
#          image: jjolon/php-74:latest
          resources:
            requests:
              memory: "Gi"
              cpu: "200m"
            limits:
              memory: "3Gi"
              cpu: "700m"
          ports:
            - containerPort: 443
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          # volumeMounts:
          #   - mountPath: "/var/www/html"
          #     name: vol-php-backend
      # volumes:
      #   - name: vol-php-backend
      #     persistentVolumeClaim:
      #       claimName: disercomi-pv-pvc-backend

---
apiVersion: v1
kind: Service
metadata:
  name: bpm-disercomi-server
  namespace: mineco-qa
  labels:
    app.kubernetes.io/name: bpm-disercomi-server
    app.kubernetes.io/part-of: bpm-disercomi-server
spec:
  type: LoadBalancer
  externalIPs:
    - 128.5.4.44
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: listener-2
      port: 443
      protocol: TCP
  selector:
    run: bpm-disercomi-server

