apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-documentos
  namespace: mineco
  labels:
    run: laravel-documentos
spec:
  replicas: 3
  selector:
    matchLabels:
      run: laravel-documentos
  template:
    metadata:
      labels:
        run: laravel-documentos
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 128.5.8.26
        searches:
          - mineco-dev.svc.cluster.local
          - svc.cluster.local 
          - cluster.local
      containers:
        - name: laravel-documentos
          image: comerciov2:latest
          resources:
            requests:
              memory: "Gi"
              cpu: "100m"
            limits:
              memory: "3Gi"
              cpu: "100m"
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 25
              protocol: TCP
            - containerPort: 587
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: "/var/www/html"
              name: vol-documento
      volumes:
        - name: vol-documento
          persistentVolumeClaim:
            claimName: documentos-mineco